#!/usr/bin/env bash

export objectName="unimportant-local/factory:factory-local/debian:jessie"

_deriveBaseImageContainerNames

_enter() {
	_run "$@"
	#_run /bin/bash "$@"
}

_runExec() {
	docker run -it --name "$containerObjectName"_"$sessionid" --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined -e LOCAL_USER_ID=`id -u $USER` --rm -v "$sharedHostProjectDir":"$sharedGuestProjectDir":rw "$imageObjectName" "$@"
}




