#!/usr/bin/env bash

export objectName="unimportant-local/factory:factory-local/debian:jessie"

_deriveBaseImageContainerNames

_enter() {
	_run "$@"
	#_run /bin/bash "$@"
}


runExec() {
	#OpenGL, Intel HD Graphics.
	docker run -it --name "$containerObjectName"_"$sessionid" --cap-add SYS_ADMIN --device /dev/fuse --security-opt apparmor:unconfined -e localPWD="$localPWD" -e LOCAL_USER_ID=`id -u $USER` --rm -e DISPLAY=$DISPLAY -v $XSOCK:$XSOCK:rw -v $XAUTH:$XAUTH:rw -e "XAUTHORITY=${XAUTH}" --device=/dev/dri:/dev/dri -v "$HOME"/Downloads:/home/user/Downloads:rw -v "$sharedHostProjectDir":"$sharedGuestProjectDir":rw "$imageObjectName" "$@"
}


