#!/bin/bash

_compileSpecial() {
	cd "$recipeDir"
	
	CC="cc -O2 -Wall -Wno-deprecated-declarations -Wno-unused-result"
	
	$CC ./AppRun.c -o AppRun
	
	cd "$scriptAbsoluteFolder"
}

#Launch internal functions as commands.
#if [[ "$1" != "" ]] && [[ "$1" != "-"* ]] && [[ ! -e "$1" ]]
if [[ "$1" == '_'* ]]
then
	"$@"
	exit "$?"
	#_stop "$?"
fi

#Stop if script is imported into an existing shell.
if [[ "${BASH_SOURCE[0]}" != "${0}" ]]
then
	return
fi
