#!/usr/bin/env bash

_standardUsrBinPatchDir() {
	
	#local binpatchLocation="$1"
	#shift
	
	find "$@" -type f -exec sed -i -e 's|/usr|././|g' {} \;
	find "$@" -type f -exec sed -i -e 's@././/bin/env@/usr/bin/env@g' {} \;
	
}

# Make binaries and related files relocatable, replace or override absolute paths.
# Prerequsites: _collectAppDir
_binpatch() {
	echo OVERRIDDEN _binpatch
	
	cd "$appDir"
	
	_standardUsrBinPatchDir usr/bin
	_standardUsrBinPatchDir usr/lib
	_standardUsrBinPatchDir usr/share -type d \( -path usr/share/guile -o -path usr/share/gEDA/scheme \) -prune -o
	
	cd "$scriptAbsoluteFolder"
}

